# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170825_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userss',
            old_name='user',
            new_name='Username',
        ),
    ]
